apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-pipeline-persistenceagent
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/hostname: amd5
      containers:
      - name: ml-pipeline-persistenceagent
        env:
        - name: NAMESPACE
          value: ''
          valueFrom: null
