# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   name: pod-manager
#   namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-manager
  namespace: default
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get","watch","list","delete"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get","watch","list","delete"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete
- apiGroups: [""] # "" indicates the core API group
  resources: ["services"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-secrets
  namespace: default
subjects:
- kind: ServiceAccount
  name: default # name of your service account
  namespace: default # this is the namespace your service account is in
roleRef:
  kind: Role
  name: pod-manager
  apiGroup: rbac.authorization.k8s.io