apiVersion: apps/v1
kind: Deployment
metadata:
  name: metadata-writer
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/hostname: amd5
      containers:
      - name: main
        env:
        - name: NAMESPACE_TO_WATCH
          value: ''
          valueFrom: null
