apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow

resources:
#- minio-deployment.yaml
- sts-minio.yaml
#- minio-pvc.yaml
- mlpipeline-minio-artifact-secret.yaml
- minio-service.yaml