apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ca-issuer
  #name: selfsigned-issuer
  namespace: cert-manager
spec:
  #selfSigned: {}
  #ca:
    #secretName: ssl-ingress-secret-ca
    #secretName: ssl-ingress-secret
  acme: 
    #server: "https://acme-v02.api.letsencrypt.org/directory"
    server: "https://acme-staging-v02.api.letsencrypt.org/directory"
    email: "alok.hom@accenture.com"
    privateKeySecretRef: 
      name: letsencrypt-staging
    solvers:
      - http01:
          ingress:
            class: nginx
#---
#apiVersion: cert-manager.io/v1
#kind: Certificate
#metadata:
#  name: my-selfsigned-ca
#  namespace: cert-manager
#spec:
#  isCA: true
#  commonName: my-selfsigned-ca
#  secretName: root-secret
#  privateKey:
#    algorithm: ECDSA
#    size: 256
#  issuerRef:
#    name: selfsigned-issuer
#    kind: ClusterIssuer
#    group: cert-manager.io
#---
#apiVersion: cert-manager.io/v1
#kind: ClusterIssuer
#metadata:
#  name: ca-issuer
#  namespace: cert-manager
#spec:
#  ca:
#    secretName: root-secret