apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - HelmRelease.yaml
  - HelmRepository.yaml
  - namespace.yaml
  - ClusterIssuer.yaml
  - cert-manager.crds.yaml
  #- sealed-secret.yaml
  #- sealed-secretCA.yaml
