apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster1-init-sql
  namespace: etl-db
data:
  init.sql: |
    CREATE DATABASE archive WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'archive')\gexec;
    \l
    CREATE USER archive_user WITH PASSWORD 'archive_user123';
    GRANT ALL PRIVILEGES ON DATABASE archive TO archive_user;
    \c archive postgres
    GRANT ALL ON SCHEMA public TO archive_user;
