apiVersion: v1
kind: ConfigMap
metadata:
  name: hippo-init-sql
  namespace: postgres-operator
data:
  init.sql: |
    GRANT ALL PRIVILEGES ON DATABASE archive TO archive-user;
    \c archive postgres
    GRANT ALL ON SCHEMA public TO archive-user;
