apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-preload-data-config
  labels:
    app: mysql
data:
  init.sql: |
    CREATE USER 'kubeflow'@'%' IDENTIFIED WITH mysql_native_password BY 'password';