apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-preload-data-config
  labels:
    app: mysql
data:
  init.sql: |
    ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'password';
