apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-preload-data-config
  labels:
    app: mysql
data:
  init.sql: |
    ALTER USER 'root'@'%' IDENTIFIED WITH mysql_native_password BY 'password';
    ALTER USER 'root'@'%' IDENTIFIED WITH caching_sha2_password BY 'password';