apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: powerdns-admin
  namespace: powerdns
spec:
  interval: 30m
  chart:
    spec:
      chart: powerdns-admin
      version: "1.2.2"
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: powerdns
      interval: 30m
  values:
    # IMPORTANT NOTE
    #
    # This chart inherits from our common library chart. You can check the default values/options here:
    # https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
    #

    image:
      # -- image repository
      repository: ngoduykhanh/powerdns-admin
      # -- image tag
      tag: v0.2.4
      # -- image pull policy
      pullPolicy: IfNotPresent

    # -- environment variables. See [undocumented configs](https://github.com/PowerDNS-Admin/PowerDNS-Admin/blob/master/configs/docker_config.py)
    # and [application docs](# https://github.com/PowerDNS-Admin/PowerDNS-Admin/blob/master/configs/development.py) for more details.
    # @default -- See below (only deviations from the default settings are specified)
    env:
      # Application Configuration
      # -- Application Timezone
      TZ: Europe/Oslo
      # -- Unique app Key
      SECRET_KEY: PowerDNSAPI
      # -- Database connection string - if not set uses internal sqlite db
      SQLALCHEMY_DATABASE_URI: "mysql://pda:pda@powerdns-mariadb/pda"  # mysql://db_user:db_pass@db_host/powerdns_admin
      # -- Timeout for Gunicorn workers
      GUNICORN_TIMEOUT: 60
      # -- How many Gunicorn workers to spawn
      GUNICORN_WORKERS: 2
      # -- Gunicorn loglevel to use
      GUNICORN_LOGLEVEL: DEBUG

    # -- Configures service settings for the chart.
    # @default -- See values.yaml
    service:
      main:
        ports:
          http:
            port: 80

    ingress:
      # -- Enable and configure ingress settings for the chart under this key.
      # @default -- See values.yaml
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
          # traefik.ingress.kubernetes.io/router.middlewares: traefik-subpath-stripprefixregex@kubernetescrd
          # cert-manager.io/cluster-issuer: ca-issuer
        #ingressClassName: # "traefik"
        hosts:
          - host: pdns-admin.systemtracker.no-ip.org
            ## Configure the paths for the host
            paths:
              # -- Path.  Helm template can be passed.
              - path: /

          # -- Configure TLS for the ingress. Both secretName and hosts can process a Helm template.
        #tls: []
          #- secretName: pdns-admin
          #  hosts:
          #  - pdns-admin.chart-example.local

    # -- Configure persistence settings for the chart under this key.
    # this persists the internal sqlite DB if no other database is enabled
    # @default -- See values.yaml
    persistence:
      data:
        enabled: false
  postRenderers:
    - kustomize:
        patches:
          # Repeat this block 15 times...
          - target:
              version: v1
              kind: Deployment
              name:  powerdns-admin
            patch: |
              - op: add
                path: "/spec/template/spec/nodeSelector"
                value:
                  kubernetes.io/hostname: amd5