---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: py-app
  namespace: py-app
spec:
  image: alokhom/python-docker
  interval: 5m
  secretRef:
    name: regcred
---
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJhbG9raG9tIiwicGFzc3dvcmQiOiJBbmFtaWthMTk3OCEiLCJlbWFpbCI6ImFsb2suaG9tQGdtYWlsLmNvbSIsImF1dGgiOiJZV3h2YTJodmJUcEJibUZ0YVd0aE1UazNPQ0U9In19fQ==
kind: Secret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: py-app
type: kubernetes.io/dockerconfigjson
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: py-apppolicy
  namespace: py-app
spec:
  imageRepositoryRef:
    name: py-app
  policy:
    semver:
      range: '^1.x'
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: py-app
  namespace: py-app
spec:
  interval: 5m0s
  url: ssh://git@github.com/alokhom/rivertyflux
  ref:
    branch: main
  secretRef:
    name: pythonapp-auth
---
apiVersion: v1
kind: Secret
metadata:
  name: pythonapp-auth
  namespace: py-app
stringData:
  identity: |
    -----BEGIN PRIVATE KEY-----
    MIHuAgEAMBAGByqGSM49AgEGBSuBBAAjBIHWMIHTAgEBBEIABSPJ/TQzhdjhmCrs
    c6uIrMRhvvSRxTHYmNOyiW3pjsJo7mrmagiYHScZ9tieJgOndcGphO6vC8jyVBcT
    mEVh5gyhgYkDgYYABADcYsxndsImDcQhXtgsoxLL14PSY+8m/ZyRtIHfEtc0cJ3d
    7yjz/i2znQvjI+Av5mhJ7fw58pl2YbcZJpC2Rn9KxgAEV351BLyazkLeqXu4R2+I
    WJcN2v1QlBbroRwDp6QAzVst7TS0lFZy8V8swiDn1cQLB5qpMwIDUBwz13pkhvgY
    mA==
    -----END PRIVATE KEY-----
  identity.pub: |
    ecdsa-sha2-nistp521 AAAAE2VjZHNhLXNoYTItbmlzdHA1MjEAAAAIbmlzdHA1MjEAAACFBADcYsxndsImDcQhXtgsoxLL14PSY+8m/ZyRtIHfEtc0cJ3d7yjz/i2znQvjI+Av5mhJ7fw58pl2YbcZJpC2Rn9KxgAEV351BLyazkLeqXu4R2+IWJcN2v1QlBbroRwDp6QAzVst7TS0lFZy8V8swiDn1cQLB5qpMwIDUBwz13pkhvgYmA==       
  known_hosts: |
    github.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg=
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: py-appupdate
  namespace: py-app
spec:
  interval: 30m
  sourceRef:
    kind: GitRepository
    name: py-app
    namespace: py-app
  git:
    commit:
      messageTemplate: |
        Automated image update
        
        Automation name: {{ .AutomationObject }}

        Files:
        {{ range $filename, $_ := .Changed.FileChanges -}}
        - {{ $filename }}
        {{ end -}}

        Objects:
        {{ range $resource, $changes := .Changed.Objects -}}
        - {{ $resource.Kind }} {{ $resource.Name }}
          Changes:
        {{- range $_, $change := $changes }}
            - {{ $change.OldValue }} -> {{ $change.NewValue }}
        {{ end -}}
        {{ end -}}   
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
    checkout:
      ref:
        branch: main
    push:
      branch: main
  update:
    path: ./apps/pyApp
    strategy: Setters
---
apiVersion: v1
data:
  token: MTlkNzllOGMyODFlNzkwNThkZDQzMDE2M2M4NmNjMjg1MDZhZDg2Ng==
kind: Secret
metadata:
  creationTimestamp: null
  name: webhook-token
  namespace: py-app
---
apiVersion: notification.toolkit.fluxcd.io/v1
kind: Receiver
metadata:
  name: py-app
  namespace: py-app
spec:
  type: dockerhub
  secretRef:
    name: webhook-token
  resources:
    - kind: ImageRepository
      name: py-apppolicy