---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: py-app
  namespace: py-app
spec:
  image: alokhom/python-docker
  interval: 30m
  secretRef:
    name: regcred
---
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJhbG9raG9tIiwicGFzc3dvcmQiOiJBbmFtaWthMTk3OCEiLCJlbWFpbCI6ImFsb2suaG9tQGdtYWlsLmNvbSIsImF1dGgiOiJZV3h2YTJodmJUcEJibUZ0YVd0aE1UazNPQ0U9In19fQ==
kind: Secret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: py-app
type: kubernetes.io/dockerconfigjson
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: py-apppolicy
  namespace: py-app
spec:
  imageRepositoryRef:
    name: py-app
  policy:
    semver:
      range: '^1.x'
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: py-app
  namespace: py-app
spec:
  interval: 5m0s
  url: https://github.com/alokhom/rivertyflux
  ref:
    branch: main
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: py-appupdate
  namespace: py-app
spec:
  interval: 30m
  sourceRef:
    kind: GitRepository
    name: py-app
    namespace: py-app
  git:
    commit:
      messageTemplate: |
        Automated image update
        
        Automation name: {{ .AutomationObject }}

        Files:
        {{ range $filename, $_ := .Changed.FileChanges -}}
        - {{ $filename }}
        {{ end -}}

        Objects:
        {{ range $resource, $changes := .Changed.Objects -}}
        - {{ $resource.Kind }} {{ $resource.Name }}
          Changes:
        {{- range $_, $change := $changes }}
            - {{ $change.OldValue }} -> {{ $change.NewValue }}
        {{ end -}}
        {{ end -}}   
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
    checkout:
      ref:
        branch: main
    push:
      branch: main
  update:
    path: ./apps/pyApp