---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: py-app
  namespace: py-app
spec:
  image: alokhom/python-docker
  interval: 5m
  secretRef:
    name: regcred
---
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJhbG9raG9tIiwicGFzc3dvcmQiOiJBbmFtaWthMTk3OCEiLCJlbWFpbCI6ImFsb2suaG9tQGdtYWlsLmNvbSIsImF1dGgiOiJZV3h2YTJodmJUcEJibUZ0YVd0aE1UazNPQ0U9In19fQ==
kind: Secret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: py-app
type: kubernetes.io/dockerconfigjson
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: py-apppolicy
  namespace: py-app
spec:
  imageRepositoryRef:
    name: py-app
  policy:
    semver:
      range: '^1.x'
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: py-app
  namespace: py-app
spec:
  interval: 5m0s
  url: ssh://git@github.com/alokhom/rivertyflux
  ref:
    branch: main
  secretRef:
    name: pythonapp-auth
---
apiVersion: v1
kind: Secret
metadata:
  name: pythonapp-auth
  namespace: py-app
stringData:
  identity: |
    -----BEGIN PRIVATE KEY-----
    MIG2AgEAMBAGByqGSM49AgEGBSuBBAAiBIGeMIGbAgEBBDB2thfGPOf58htRpBYw
    if6qhJXGUC4p6b0GjBeN1CTPUgQsy+3pNX+A5ykwP66+gEuhZANiAAQilWo3elT1
    yAmO8eTVXtquYvUbuHn/2m3rZ37l+7h7XPNgJvABAr3U9/Y3PXqxy+/0jmuN80yG
    5aA23shkNurwFPVZWd/60DB9ZVUoos2fX0tZEutLQTDOHOilJlz9+5k=
    -----END PRIVATE KEY-----
  identity.pub: |
    ecdsa-sha2-nistp384 AAAAE2VjZHNhLXNoYTItbmlzdHAzODQAAAAIbmlzdHAzODQAAABhBCKVajd6VPXICY7x5NVe2q5i9Ru4ef/abetnfuX7uHtc82Am8AECvdT39jc9erHL7/SOa43zTIbloDbeyGQ26vAU9VlZ3/rQMH1lVSiizZ9fS1kS60tBMM4c6KUmXP37mQ==
  known_hosts: github.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: py-appupdate
  namespace: py-app
spec:
  interval: 30m
  sourceRef:
    kind: GitRepository
    name: py-app
    namespace: py-app
  git:
    commit:
      messageTemplate: |
        Automated image update
        
        Automation name: {{ .AutomationObject }}

        Files:
        {{ range $filename, $_ := .Changed.FileChanges -}}
        - {{ $filename }}
        {{ end -}}

        Objects:
        {{ range $resource, $changes := .Changed.Objects -}}
        - {{ $resource.Kind }} {{ $resource.Name }}
          Changes:
        {{- range $_, $change := $changes }}
            - {{ $change.OldValue }} -> {{ $change.NewValue }}
        {{ end -}}
        {{ end -}}   
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
    checkout:
      ref:
        branch: main
    push:
      branch: main
  update:
    path: ./apps/pyApp
    strategy: Setters
---
apiVersion: v1
data:
  token: MTlkNzllOGMyODFlNzkwNThkZDQzMDE2M2M4NmNjMjg1MDZhZDg2Ng==
kind: Secret
metadata:
  creationTimestamp: null
  name: webhook-token
  namespace: py-app
---
apiVersion: notification.toolkit.fluxcd.io/v1
kind: Receiver
metadata:
  name: py-app
  namespace: py-app
spec:
  type: dockerhub
  secretRef:
    name: webhook-token
  resources:
    - kind: ImageRepository
      name: py-apppolicy