apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: py-app
  namespace: py-app
  labels:
    app: py-app
spec:
  selector:
    matchLabels:
      app: py-app
  endpoints:
  - port: py-appweb