apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: py-app
  namespace: py-app
  labels:
    pod-monitor: py-app
spec:
  selector:
    matchLabels:
      app: py-app
  podMetricsEndpoints:
  - port: py-appweb
