apiVersion: v1
kind: ConfigMap
metadata:
  name: flytepg-init-sql
  namespace: flyte-core
data:
  init.sql: |
    GRANT ALL PRIVILEGES ON DATABASE flytepg TO flytepg-user;
    GRANT ALL PRIVILEGES ON DATABASE flytepg TO pgbouncer;
    \c flytepg postgres
    GRANT ALL ON SCHEMA public TO flytepg-user;
    GRANT ALL ON SCHEMA public TO pgbouncer;
    create schema json_demo;
