apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PGAdmin
metadata:
  name: flytepg
  namespace: flyte-core
spec:
  dataVolumeClaimSpec:
    storageClassName: "local-path"
    accessModes:
    - "ReadWriteOnce"
    resources:
      requests:
        storage: 5Gi
  serverGroups:
    - name: supply
      # An empty selector selects all postgresclusters in the Namespace
      postgresClusterSelector: {}
    - name: demand
      postgresClusterSelector:
        matchLabels:
          postgres-operator.crunchydata.com/cluster: hippo