apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./nginx
  - ./bitnami_airflow
  - ./prometheus
  - ./etl-db
  - ./mtce
  #- ./kubeFlow
  # - ./chromadb
  - ./longhorn
  #- ./flyte
  - ./sqllite3
  - ./cert-manager
  - ./powerdns
  - ./open-telemetry
  - ./ambientmesh