apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # apps
  - ./sqllite3-rqlite
  # ingress
  - ./nginx
  #- ./ambientmesh
  - ./consul
  # data processing
  - ./bitnami_airflow
  # monitoring and mtce cleanup
  - ./prometheus
  - ./mtce
  - ./powerdns
  - ./open-telemetry
  - ./cert-manager
  # machine learning
  #- ./kubeFlow
  # - ./chromadb
  # storage
  - ./longhorn
  # not sure what it is 
  #- ./flyte


