apiVersion: v1
kind: ConfigMap
metadata:
  name: airflow-configuration
  namespace: airflow
  labels:
    app.kubernetes.io/instance: airflow
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: airflow
    app.kubernetes.io/version: 2.10.3
    helm.sh/chart: airflow-21.5.1
    helm.toolkit.fluxcd.io/name: airflow
    helm.toolkit.fluxcd.io/namespace: airflow
  annotations:
    meta.helm.sh/release-name: airflow
    meta.helm.sh/release-namespace: airflow
data:
  airflow.cfg: >-
    [core]
    load_examples=True
    dags_folder=/opt/bitnami/airflow/dags
    executor=KubernetesExecutor

    [logging]
    colored_console_log=True

    [scheduler]
    standalone_dag_processor=False

    [triggerer]
    default_capacity=1000

    [metrics]
    # StatsD (https://github.com/etsy/statsd) integration settings.
    # Enables sending metrics to StatsD. Make sure you change the port from 8125 to 9125
    statsd_on = True
    statsd_host = statsd-prometheus-statsd-exporter.prometheus
    statsd_port = 9125
    statsd_prefix = airflow
    metrics_allow_list = scheduler,executor,dagrun,pool,triggerer

    [webserver]
    web_server_port=8080

    [kubernetes_executor]
    namespace=airflow
    worker_container_repository=docker.io/bitnami/airflow
    worker_container_tag=2.10.3-debian-12-r1
    delete_worker_pods=True
    delete_worker_pods_on_failure=True
    pod_template_file="/opt/bitnami/airflow/pod_template.yaml"
