apiVersion: v1
data:
  AIRFLOW_DATABASE_PASSWORD: Ym5fcGFzczEyMw==
  #AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: cG9zdGdyZXNxbDovL2JuX2FpcmZsb3c6Ym5fcGFzczEyM0BwZy1wb3N0Z3Jlc3FsLmRhdGFiYXNlL2JpdG5hbWlfYWlyZmxvdw==
  AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: cG9zdGdyZXNxbCtwc3ljb3BnMjovL2JuX2FpcmZsb3c6Ym5fcGFzczEyM0BwZy1wb3N0Z3Jlc3FsLmRhdGFiYXNlL2JpdG5hbWlfYWlyZmxvdw==
kind: Secret
metadata:
  creationTimestamp: null
  name: airflow-envvar
  namespace: airflow